#!/bin/bash
echo "[+] Starting Comprehensive Red Team Auditd Rule Tester"
echo "[!] Warning: This script will trigger multiple auditd rules!"
echo "[!] Run it in a controlled environment."

echo '[+] Testing Execution Monitoring...'
echo 'Executing: /usr/sbin/service --version'
/usr/sbin/service --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/chef-client --version'
/usr/bin/chef-client --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/kubectl --version'
/usr/bin/kubectl --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/sudo --version'
/usr/bin/sudo --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/sbin/setcap --version'
/usr/sbin/setcap --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /bin/su --version'
/bin/su --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/nsenter --version'
/usr/bin/nsenter --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/sbin/iptables-restore --version'
/usr/sbin/iptables-restore --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/ncat --version'
/usr/bin/ncat --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/socat --version'
/usr/bin/socat --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/openssl --version'
/usr/bin/openssl --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/proxychains --version'
/usr/bin/proxychains --version 2>/dev/null || echo 'Failed to execute'
echo 'Executing: /usr/bin/kubectl --version'
/usr/bin/kubectl --version 2>/dev/null || echo 'Failed to execute'

echo '[+] Testing File Monitoring...'
echo 'Writing to: /home/'
echo 'auditd test' >> /home/ 2>/dev/null || echo 'Failed to write to /home/'
echo 'Writing to: /var/spool/cron/crontabs'
echo 'auditd test' >> /var/spool/cron/crontabs 2>/dev/null || echo 'Failed to write to /var/spool/cron/crontabs'
echo 'Writing to: /home/'
echo 'auditd test' >> /home/ 2>/dev/null || echo 'Failed to write to /home/'
echo 'Writing to: /lib64/security'
echo 'auditd test' >> /lib64/security 2>/dev/null || echo 'Failed to write to /lib64/security'
echo 'Writing to: /home/'
echo 'auditd test' >> /home/ 2>/dev/null || echo 'Failed to write to /home/'
echo 'Writing to: /usr/bin/passwd'
echo 'auditd test' >> /usr/bin/passwd 2>/dev/null || echo 'Failed to write to /usr/bin/passwd'
echo 'Writing to: /lib/modules'
echo 'auditd test' >> /lib/modules 2>/dev/null || echo 'Failed to write to /lib/modules'
echo 'Writing to: /root/.bash_history'
echo 'auditd test' >> /root/.bash_history 2>/dev/null || echo 'Failed to write to /root/.bash_history'
echo 'Writing to: /home/'
echo 'auditd test' >> /home/ 2>/dev/null || echo 'Failed to write to /home/'
echo 'Writing to: /etc/sysconfig/iptables'
echo 'auditd test' >> /etc/sysconfig/iptables 2>/dev/null || echo 'Failed to write to /etc/sysconfig/iptables'
echo 'Writing to: /etc/sysconfig/ip6tables'
echo 'auditd test' >> /etc/sysconfig/ip6tables 2>/dev/null || echo 'Failed to write to /etc/sysconfig/ip6tables'
echo 'Writing to: /etc/audit/auditd.conf'
echo 'auditd test' >> /etc/audit/auditd.conf 2>/dev/null || echo 'Failed to write to /etc/audit/auditd.conf'
echo 'Writing to: /etc/systemd/journald.conf'
echo 'auditd test' >> /etc/systemd/journald.conf 2>/dev/null || echo 'Failed to write to /etc/systemd/journald.conf'
echo 'Writing to: /etc/resolv.conf'
echo 'auditd test' >> /etc/resolv.conf 2>/dev/null || echo 'Failed to write to /etc/resolv.conf'
echo 'Writing to: /etc/nsswitch.conf'
echo 'auditd test' >> /etc/nsswitch.conf 2>/dev/null || echo 'Failed to write to /etc/nsswitch.conf'

echo '[+] Testing Network Commands...'
